version: '3.4'
services:
    nginx:
        image: nginx:1.13.8-alpine
        networks:
            access:
        volumes:
            - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/nginx/conf.d:/etc/nginx/conf.d:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s

    etcd:
        image: daocloud.io/buxiaomo/etcd:3.2.9
        networks:
            access:
        volumes:
            - /var/lib/etcd/default:/etcd:rw
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
        command: --name etcd --data-dir /etcd --advertise-client-urls http://0.0.0.0:4001 --initial-advertise-peer-urls http://0.0.0.0:7001

    etcd-browser:
        image: daocloud.io/buxiaomo/etcd-browser:master-cccf57a
        environment:
            - ETCD_HOST=127.0.0.1
            - ETCD_PORT=4001
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s

    confd:
        image: daocloud.io/buxiaomo/confd:0.15.0-docker
        networks:
            access:
        volumes:
            - /etc/confd/templates:/etc/confd/templates
            - /etc/confd/conf.d:/etc/confd/conf.d
            - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /var/run/docker.sock:/var/run/docker.sock:ro
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
        command: confd -interval=30 -backend etcd -node http://127.0.0.1:4001

networks:
    access:
        external:
            name: "host"
